import type { Metadata } from "next";
import localFont from "next/font/local";
import ReduxProvider from "@/components/ReduxProvider";
import { TanstackProvider } from "@/providers/tanstak.provider";
import { ToastifyProvider } from "@/providers/toastify.provider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "پیتزا نوشا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ReduxProvider>
        <ToastifyProvider>
          <TanstackProvider>
           
            {children}
            
          </TanstackProvider>
        </ToastifyProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
